test: &default

  # Credentials for REST APIs
  client_id: Aa-9AHr9lL_-9rgcuWS6v0VxCjdlMpsdkjhzA_MsNbkUMP3Ei493jACvIScyzagcaChn-x0Yio5uKzoM
  client_secret: EGbDtty1Vi2FB_01pLFUqLnpWtEESQ-YV6CXrOtr4TnBlA3gyM8NaP_U3Ir8E_fNnoiKOVynRRY73LvJ

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: namakaloya@uv.com
  
  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
